### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Ika-Taro** [Ika-Taro/protospace-37499#1]
Web URL:        https://protospace-37499.herokuapp.com/

**Comment by yusuketono** [comment]
@Ika-Taro さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
ご提出いただいたURLを開くと、エラー画面が表示されてしまいます。
`https://protospace-37499.herokuapp.com/`
**※ 動作確認ができていない為、次回ご提出時に確認させていただきます。**

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by snkw-works** [comment]
@Ika-Taro さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
##### プロトタイプ一覧表示機能
- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移するよう修正しましょう**
「プロトタイプ名」をクリックすると、プロトタイプ詳細ページではなくユーザー詳細ページに遷移してしまいます。

##### ユーザー詳細機能
- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
コメント投稿者名をクリックすると、そのユーザーではなくプロトタイプ投稿者のユーザー詳細ページに遷移してしまいます。

- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるよう修正しましょう**
「役職」の欄に「プロフィール」の情報が表示されてしまいます。

##### その他
- [x] **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できるよう修正しましょう**
ログアウト状態のユーザーは「プロトタイプ詳細ページ」に遷移できない状態です。

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるよう修正しましょう**
他のユーザーのプロトタイプ編集ページに遷移できてしまいます。

※ログアウト状態での挙動に関しては一部動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by wakazo228** [comment]
@Ika-Taro さん、ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

##### プロトタイプ一覧表示機能
- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移するよう修正しましょう**
ログアウト状態で一覧表示されている画像およびプロトタイプ名をクリックすると、一部のプロトタイプでは下記のエラーが表示されてしまいます。
<img width="641" alt="スクリーンショット 2022-02-17 13 05 00" src="https://user-images.githubusercontent.com/53425908/154403349-c2aff03b-9a7a-4f9d-bc40-3b240f60459f.png">
※エラーが発生するプロトタイプ（下記赤枠のもの）
<img width="900" alt="スクリーンショット 2022-02-17 13 09 26" src="https://user-images.githubusercontent.com/53425908/154403667-73d21e83-caa8-4bb2-9400-f9c9aba4ca87.png">

##### ユーザー詳細機能
- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
コメント投稿者名をクリックすると、そのユーザーではなく”ログインしているユーザー”のユーザー詳細ページに遷移してしまいます。
<img width="641" alt="スクリーンショット 2022-02-17 13 12 30" src="https://user-images.githubusercontent.com/53425908/154404182-fd6986bd-8ec3-41e8-9225-e13bb465fd6d.png">

##### その他
- [x] **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できるよう修正しましょう**
ログアウト状態のユーザーは「プロトタイプ詳細ページ」に遷移できない状態です。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by wakazo228** [comment]
@Ika-Taro さん、修正とご提出ありがとうございます！
正常に動作することが確認できました！ **LGTM**です✨
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう(^^)

**Comment by Ika-Taro** [comment]
ありがとうございました
